version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      # Mount backend code for live reloading during development
      - ./backend:/app
      # Preserve node_modules in container
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
    command: npm run dev
    stdin_open: true
    tty: true

  frontend:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev -- --host"
    stdin_open: true
    tty: true
    depends_on:
      - backend
